### ISSUE TITLE
iOS - no longer possible to add Czech language file

### ISSUE THREAD

**Issue by rdolezel** [JimmyS83/telegram-cz-translation#1]
Ca you please confirm if you are able to add Czech language to the current iOS app on iOS 12?

Thanks

Radek

**Comment by JimmyS83** [comment]
Hello,
I am planning update also iOS / Android soon, not sure about version (I am using CIS files). But from the name I am guessing, they replace old good application by Telegram X / Swift; I am not sure, if there is possibility to apply custom language pack (?). I dont have Iphone to test, but if they disable this option, then its problem, which would need to be adressed (pressed) somewhere else :(

**Comment by JimmyS83** [comment]
> 
> 
> Ca you please confirm if you are able to add Czech language to the current iOS app on iOS 12?
> 
> Thanks
> 
> Radek

Could you confirm, that you cant install custom language file to the iOS application, following this guide: https://karty.php5.cz/telegram/#ios ?

**Comment by rdolezel** [comment]
Yes, unfortunately I am not able to install it on iOS 12. I am new to Telegram (account created 3 days ago), I installed official application version 5. I am afraid your custom language file was prepared for version 4, right? I am not able to find any 3 dots in the interface and there is not option to install it. I will add two screenshots.
![img_4355](https://user-images.githubusercontent.com/6695609/46540068-94c0c880-c8b8-11e8-9885-087a0fe33790.PNG)
![photo_2018-10-05_16-02-59](https://user-images.githubusercontent.com/6695609/46540069-94c0c880-c8b8-11e8-9705-bdeb08ec95fe.jpg)

**Comment by JimmyS83** [comment]
Thanks for information. Thats really bad then. They recently replaced Original Telegram application (on Android found as Telegram) by swift version (on Android Telegram X) on iOS platform. Seems that Telegram X lacks this important feature. 

I am really afraid, that similiar faith could be also for Android users in future. I am using Android version, so I dont have iPhone experience from first hand, but if they some day force Telegram X as main (and only?) app for Android, I will stay on old version and Czech language.

They have official translation platform, but despite (not only mine) efforts, they doesnt add Czech language. We have almost 100% strings ALREADY translated, but - I really dont know why - we still cant participate on the OFFICIAL (that means avaible form original app menu) translation :(  I contacted their developers on github, and even they dont know, why Czech wasnt offered as language, on which we can participate. And I have no answer from official Telegram "contacts" :(

**Comment by rdolezel** [comment]
Don't you know why Czech.strings file for iOS differs so much on this page https://tlgrm.ru/locales/list when compared to your file?

**Comment by JimmyS83** [comment]
> 
> 
> Don't you know why Czech.strings file for iOS differs so much on this page https://tlgrm.ru/locales/list when compared to your file?

There is some delay to generate files there.. You can see, that they are 3 months old I think. Usually they update it in some time..

**Comment by JimmyS83** [comment]
I updated Readme, and also webpage http://telegram.zde.cz, to reflect latest negative changes regarding Telegram on iOS. I hope Apple users can also choose, which version they instal to the iPhone, similiar as Android users :(
